/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiX402RouteImport } from './routes/api/x402'
import { Route as ApiAgentIndexRouteImport } from './routes/api/agent/index'
import { Route as ApiAgentSplatRouteImport } from './routes/api/agent/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiX402Route = ApiX402RouteImport.update({
  id: '/api/x402',
  path: '/api/x402',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentIndexRoute = ApiAgentIndexRouteImport.update({
  id: '/api/agent/',
  path: '/api/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentSplatRoute = ApiAgentSplatRouteImport.update({
  id: '/api/agent/$',
  path: '/api/agent/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/x402': typeof ApiX402Route
  '/api/agent/$': typeof ApiAgentSplatRoute
  '/api/agent/': typeof ApiAgentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/x402': typeof ApiX402Route
  '/api/agent/$': typeof ApiAgentSplatRoute
  '/api/agent': typeof ApiAgentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/x402': typeof ApiX402Route
  '/api/agent/$': typeof ApiAgentSplatRoute
  '/api/agent/': typeof ApiAgentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/mcp' | '/api/x402' | '/api/agent/$' | '/api/agent/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/mcp' | '/api/x402' | '/api/agent/$' | '/api/agent'
  id:
    '__root__' | '/' | '/api/mcp' | '/api/x402' | '/api/agent/$' | '/api/agent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiX402Route: typeof ApiX402Route
  ApiAgentSplatRoute: typeof ApiAgentSplatRoute
  ApiAgentIndexRoute: typeof ApiAgentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x402': {
      id: '/api/x402'
      path: '/api/x402'
      fullPath: '/api/x402'
      preLoaderRoute: typeof ApiX402RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/': {
      id: '/api/agent/'
      path: '/api/agent'
      fullPath: '/api/agent/'
      preLoaderRoute: typeof ApiAgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/$': {
      id: '/api/agent/$'
      path: '/api/agent/$'
      fullPath: '/api/agent/$'
      preLoaderRoute: typeof ApiAgentSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiX402Route: ApiX402Route,
  ApiAgentSplatRoute: ApiAgentSplatRoute,
  ApiAgentIndexRoute: ApiAgentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
